---
  wem_agent_versions:
    2006:
      install_arguments: /quiet Cloud=0
      product_id: '{3E82149F-130C-49AB-B067-539851AE66E3}'
    2009:
      install_arguments: /quiet Cloud=0
      product_id: '{C14EE685-0538-4778-9B52-AD4C8B934040}'
    2012:
      install_arguments: /quiet Cloud=0
      product_id: '{4A001FDB-9C71-48B3-8A39-311F1317C042}'
    2103:
      install_arguments: /quiet Cloud=0
      product_id: '{FBF14783-5F94-4B02-ACA7-063AE03991D9}'

  smb_location: \\file1\automation

  wem_agent_version: 2103
  wem_agent_smb_location: "{{ smb_location }}\\Citrix\\Workspace Environment Management\\{{ wem_agent_version }}"
  wem_agent_install_file: Citrix Workspace Environment Management Agent Setup.exe
  wem_agent_install_arguments: "{{ wem_agent_versions[wem_agent_version].install_arguments }}"
  wem_agent_product_id: "{{ wem_agent_versions[wem_agent_version].product_id }}"
  wem_agent_install_state: present
