---
galaxy_info:
  role_name: install_broker
  author: Joe Shonk
  description: Install the Citrix Workspace Environment Management Broker
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - 2016
     - 2019

  galaxy_tags:
    - wem
    - broker
