---
  - name: "Install WEM Agent Version {{ wem_agent_version }}"
    win_package:
      path: "{{ wem_agent_smb_location }}\\{{ wem_agent_install_file }}"
      product_id: "{{ wem_agent_product_id }}"
      arguments: "{{ wem_agent_install_arguments }}"
      state: "{{ wem_agent_install_state }}"
      user_name: "{{ ansible_become_user }}"
      user_password: "{{ ansible_become_pass }}"
