---
  - name: "Install WEM Infrastructure Broker Version {{ wem_broker_version }}"
    win_package:
      path: "{{ wem_broker_smb_location }}\\{{ wem_broker_install_file }}"
      product_id: "{{ wem_broker_product_id }}"
      arguments: "{{ wem_broker_install_arguments }}"
      state: "{{ wem_broker_install_state }}"
      user_name: "{{ ansible_become_user }}"
      user_password: "{{ ansible_become_pass }}"
